language: ruby

dist: trusty

script: npm i && bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

deploy:
  provider: pages
  keep_history: true
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: _site
  on:
    branch: master

cache:
  bundler: true
  directories:
  - /home/travis/.rvm/
  - node_modules
  - vendor/bundle
