title: "Getworklounge.io"
description: "WorkLounge is a members-only business club, lounge, meeting, and flexible office space."
url: "https://Getworklounge.io"
email: service@esteemed.io
recaptcha_api_key: 6LcC3KAhAAAAAMSRHTEA2IdzlbNBRGiWBoGprcfc
meta:
  image: "/img/main-hero.svg"
google_analytics: UA-167435008-1
twitter:
  username: EsteemedTalent
facebook:
  publisher: Esteemed-106526290944059
logo: /img/workloungelogo.svg
social:
  links:
    - https://www.facebook.com/Esteemed-106526290944059/
    - https://twitter.com/EsteemedTalent
    - https://www.linkedin.com/company/esteemed/

# Build settings
markdown: kramdown
exclude:
  - docker-compose.yml
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
author_dir: "blog/author"
author_title_suffix: ""
collections:
  press:
    output: true
  case_study:
    output: true
pagination:
  enabled: true
  per_page: 10
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  title: ':cat Posts'
  categories:
    layouts:
      - 'categories.html'
    permalink: "/blog/category/:cat/"
  collections:
    enabled: false
  tags:
    enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/img/main-esteemed.jpg"
      contact_form: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      image: "/img/default-blog.jpg"
  - scope:
      path: ""
      type: "press"
    values:
      layout: "post"
      permalink: /:title/
  - scope:
      path: ""
      type: "case_study"
    values:
      layout: "post"
      permalink: /:title/
