title: "Esteemed.io"
description: >-
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "img/esteemed-main-meta.png"

# Build settings
markdown: kramdown
plugins:
  - jekyll-menus

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Google Analytics
google_analytics: UA-167435008-1
