title: "Esteemed.io"
description: >-
url: "https://www.esteemed.io"
email: interview@esteemed.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-menus

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
