title: "Esteemed.io"
description: >-
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "/img/esteemed-main-meta.png"
google_analytics: UA-167435008-1
twitter:
  username: EsteemedTalent
facebook:
  publisher: Esteemed-106526290944059
logo: /img/esteemed-bw-logo.png
social:
  links:
    - https://www.facebook.com/Esteemed-106526290944059/
    - https://twitter.com/EsteemedTalent
    - https://www.linkedin.com/company/esteemed/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
author_dir: "blogs/author"
author_title_prefix: "Blog - By "
pagination:
  enabled: true
  per_page: 10
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  title: ':cat Posts'
  categories:
    layouts:
      - 'categories.html'
    permalink: "/blogs/category/:cat/"
  collections:
    enabled: false
  tags:
    enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/img/esteemed-main-meta.png"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      sitemap: false
