title: "Esteemed.io"
description: "Best-in-class, Esteemed is the fastest-growing AI-powered talent management and career solutions provider delivering frictionless hiring and talent incubation for digital professionals."
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "/img/main-hero.svg"
google_analytics: UA-167435008-1
twitter:
  username: EsteemedTalent
facebook:
  publisher: Esteemed-106526290944059
logo: /img/esteemed-bw-logo.svg
social:
  links:
    - https://www.facebook.com/Esteemed-106526290944059/
    - https://twitter.com/EsteemedTalent
    - https://www.linkedin.com/company/esteemed/

# Build settings
markdown: kramdown
exclude:
  - docker-compose.yml
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-webp
author_dir: "blog/author"
author_title_suffix: ""
collections:
  press:
    output: true
  case-studies:
    output: true
pagination:
  enabled: true
  per_page: 10
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  title: ':cat Posts'
  categories:
    layouts:
      - 'categories.html'
    permalink: "/blog/category/:cat/"
  collections:
    enabled: false
  tags:
    enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/img/main-esteemed.jpg"
      contact_form: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      image: "/img/default-blog.jpg"
  - scope:
      path: ""
      type: "press"
    values:
      layout: "post"
      permalink: /:title/
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: "post"
      permalink: /:title/
webp:
  enabled: true
  quality: 75
  img_dir: ["/img/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png"]
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false
