---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Blog
  create: documents
  match: "**/*"
- type: document
  path: index.html
  label: Homepage
- type: document
  path: company.html
  label: Company
- type: document
  path: terms-of-use.md
  label: Terms of Use
- type: document
  path: privacy-policy.md
  label: Privacy Policy
- type: directory
  path: _authors
  label: Authors
  create: documents
  match: "**/*"
- type: directory
  path: _categories
  label: Categories
  create: documents
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
