---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*"
- type: heading
  label: Content
- type: jekyll-posts
  label: Blog
  create: documents
  templates:
  - blog
- type: directory
  path: _press
  label: Press
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: _case_study
  label: Case Study
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: heading
  label: Pages
- type: document
  path: index.html
  label: Homepage
- type: document
  path: _data/ctas.yml
  label: CTAs
- type: document
  path: pages/events.html
  label: Events
- type: document
  path: pages/learn-more.html
  label: Learn More
- type: document
  path: pages/faqs.html
  label: FAQs
- type: document
  path: pages/about_us/company.html
  label: Company
- type: document
  path: pages/member-compensation-plan.html
  label: Compensation Plan
- type: document
  path: terms-of-use.md
  label: Terms of Use
- type: document
  path: privacy-policy.md
  label: Privacy Policy
- type: document
  path: code-of-conduct.md
  label: Code of Conduct
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
