name: HTML Proofer
on:
  push:
    branches: develop
  pull_request:
    branches: develop
jobs:
  checklinks:
    name: HTMLProofer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        id: bundler-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses:  lemonarc/jekyll-action@1.0.0
      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./_site"
          arguments: "--allow-hash-href --http-status-ignore 999 --url-ignore https://money.usnews.com/money/blogs/outside-voices-careers/2015/08/19/5-things-your-resume-is-not,https://events.drupal.org/europe2021/registration-information,https://events.drupal.org/europe2021/schedule/all,https://events.drupal.org/europe2021/sessions/building-mindset-technical-leadership-workshop,https://events.drupal.org/europe2021/sessions/finding-drupal-talent-sellers-market,https://events.drupal.org/europe2021/sessions/machine-learning-drupal-tensorflowjs,https://learnmore.monster.com/future-of-work,https://www.monster.com/career-advice/article/tech-talent-gap-survey-0816"
