name: Esteemed
on:
  push:
    branches: develop
  pull_request:
    branches: develop
jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@0.5.0
